### ISSUE TITLE
Logic to determine "summary" (and other) output tables 

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#24]
@escoach Now that we have the SQL and math designed for each of the examples in the PDF mockup, I'm working to generalize the SQL and math for all possible use cases.

First, I'm working to generalize the logic for displaying a "summary' data table.

I'm defining a "summary" data table as the situation where the data table includes a list of "What" (#8), or "Who" (#11), or "Where" (#17) options. (as opposed to just showing a single "What" or "Selected activities")

Best I can tell, the logic for displaying a "summary" table should be something like:

- When there is no "What" selection regardless of what is selected in "Who" or "Where" THEN display the "What summary" (similar to #8).
- When there is no "Where" selection AND "Who" = "Any interaction" AND there is a single "What" selection, THEN display the "Who summary" (similar to #11). _Can we also use the "Who summary" when there are multiple "What" selections in this situation?_
- When there is no "Who" selection AND "Where" = "Anyplace" AND there is a single "What" selection, THEN display the "Where summary" (similar to #17). _Can we also use the "Where summary" when there are multiple "What" selections in this situation?_

This is important to nail down, because as we've seen while we've been designing the SQL, the queries can be quite different depending on the output table needed. So, we need to nail down the logic for displaying the various types of tables.

Once we figure out the logic of when to output the "summary" data tables, we'll need to define the logic for when to use non-"summary" data tables. 

For example, #18 and #19 data tables are very similar - #18 is a single "What" while #19 is multiple "What"s. 

But, we're going to have to define the logic for situations like:

1. Multiple "What" values, single "Who", single "Where".
2. Single "What", single "Who" and "Where = Anyplace". 

This is where things are going to get a bit tricky, because the various SQL for each of the mockup examples is so different. This task of defining the logic will allow us to efficiently implement code to build the proper SQL in order to provide the proper data table output, know what I mean?

I believe that we're not allowing multi-select on "Who" or "Where" (only "What"), please confirm.

thanks,
-mike

**Comment by escoach** [comment]
@ultimike 
See my responses after your text. 

When there is no "What" selection regardless of what is selected in "Who" or "Where" THEN display the "What summary" (similar to #8).
_Alberto: I agree. To be more specific, if a user does NOT select a "What", even if the user selects either "Who" or "Where", the user will see the same chart displayed in #8._  

When there is no "Where" selection AND "Who" = "Any interaction" AND there is a single "What" selection, THEN display the "Who summary" (similar to #11). Can we also use the "Who summary" when there are multiple "What" selections in this situation?
_Alberto: Yes. In other words, a user can select as many "What" items as they want AND "Who" = "Any interactions" to display a chart similar to #11. Note that if they select "Who", they should not be able to select "Where" (and vice versa). Also, when we say "Who" we mean "Who or Who Else"_

When there is no "Who" selection AND "Where" = "Anyplace" AND there is a single "What" selection, THEN display the "Where summary" (similar to #17). Can we also use the "Where summary" when there are multiple "What" selections in this situation?
_Alberto: Yes. Same comments as above_

[....]

For example, #18 and #19 data tables are very similar - #18 is a single "What" while #19 is multiple "What"s.
_Alberto: You are right. In other words, #18 is a special case of #19 because it includes only one "What" item. But the idea is that users can pick as many "What" items as they want, potentially all of them._

[...]
But, we're going to have to define the logic for situations like:

Multiple "What" values, single "Who", single "Where".
Single "What", single "Who" and "Where = Anyplace".
_Alberto: Here is how I would envision this: 
- As a user, I can select as many "What" items and as many "Who" items as I need. 
- I can select as many "What" items and as many "Where" items as I need. 
- But I can't select "What" and both "Who" and "Where" items. 
- Regardless of my selections, the charts will look like #18 and #19. 

In more simple terms, we are interested in visualizing these three scenarios:
- "What" practitioners are doing, regardless of with "Who" they interact with or "Where" they are i.e. #8.
- With "Who" practitioners interact with when they are engaged in one or more "What" activities i.e. #11.
- "Where" practitioners are when they are engaged in one or more "What" activities i.e. #17.
We do not envision for now to display the scenario in which a user can select "What", "Who", and "Where" simultaneously. Rationale: We believe that the system does not have enough data and also to keep things simple. 

[...]

I believe that we're not allowing multi-select on "Who" or "Where" (only "What"), please confirm.
_Alberto: I believe that my answers above address this issue._ 

I hope that I addressed all your questions or let me know.
Thank you very much for your questions and for moving this project forward.
Have a great weekend.

**Comment by ultimike** [comment]
@escoach My thoughts:

1. Good to know that if a "Who" is selected then a "Where" cannot be selected (and vice-versa) - this was news to me.
2. "Who" and "Where" are multi-select. 
2. Since #18 and #19 are so similar, I'd like to always use the text "Selected activities" regardless of if there is one or more selected "What"s.

-mike

**Comment by escoach** [comment]
@ultimike 
See my responses in Italics after your text.

1. Good to know that if a "Who" is selected then a "Where" cannot be selected (and vice-versa) - this was news to me.

_Alberto: I am glad we clarified. Thank you for your patience that this aspect was not very clear at the beginning._

2. "Who" and "Where" are multi-select.

_Alberto: Yes, meaning that users can pick one or more items under the What, Who, and Where. What changes is the chart that they will see._ 

3. Since #18 and #19 are so similar, I'd like to always use the text "Selected activities" regardless of if there is one or more selected "What"s.

_Alberto: Makes sense. We can ditch #18 as it is just a special case of #19._

1. Are "Who" = "Any interaction" and "Where" = "Anyplace" equivalent to not selecting "Who" or "Where"?

_Alberto: I would say no. The user must select "Any interaction" if they want to see #11. Or must select "Anyplace" to see #17. If the user selects one or more "What" but does NOT select either "Any interaction" or "Anyplace", then they will see #19. _   

2. I'm still a bit confused as to what the data table will look like if "What" has one or more selections and "Who" or "Where" has a single non-"Any" selection. The same as #18 or #19? What if there are multiple "Who" or "Where" selected?

_Alberto: If a user selects one or more "What" and one or more "Who", the table will look like #19. Same thing if instead of "Who", the user picks one or more "Where". Let me know if this is confusing.

As a summary, here are the possible scenarios I can think of:
1. A user selects nothing: then they see #8 (default opening screen)
2. A user selects one or more "What" and "Any interactions" (Under "Who"): Then they see #11 
3. A user selects one or more "What" and "Anywhere" (Under "Where"): Then they see #17 
4. A user selects one or more "What" and one or more "Who": Then they see #19
5. A user selects one or more "What" and one or more "Where": Then they see #19
6. A user selects one or more What and nothing else: Then they see #19
7. A user selects one or more "What", one or more "Who" and one or more "Where": "Error message", It is impossible to select both "Who" and "Where"_

**Comment by ultimike** [comment]
@escoach Does this logic work for you?

Proposed logic for output tables (based on previous discussion):

- If ("Timeframe" = up-to-date), then
  - If ("What" = null), then display "What summary" (similar to #8).
    - Else If ("Who" = "Any interactions"), then display "Who summary" (similar to #11).
      - Else If ("Where" = "Anyplace"), then display "Where summary" (similar to #17).
        - Else display "Selected activities" (similar to #19). 

-mike

**Comment by escoach** [comment]
@ultimike 
Yes it makes sense. The output type (#8, 11, 17, and 19) is correctly associated with each line of the script. I should say that I do not know enough about programming, so I might miss some details. But in general, the script looks correct to me. 
Hope this helps

**Comment by ultimike** [comment]
@mgcobblestone I've created [a new wiki page](https://github.com/communityinclusion/escoach/wiki/Logic-for-determining-which-Dashboard-query-to-use) for the canonical source of logic for knowing when to use each query (similar to my comment from May 18 above). This way, you don't have to go hunting through the various issues to find the logic of truth.

-mike

**Comment by ultimike** [comment]
All done here. Closing.
