### ISSUE TITLE
Discrepancies in "Who summary"

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#45]
@escoach spawning this off from #43 

I compared your example 1 ("Who summary") from your [Google Sheet](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=0) and found some discrepancies. 

Please take a look at the "Who summary (1 query)" tab from [my Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=1064923334) and you'll see a few cells in red (larger discrepancy) and yellow (smaller discrepancy). 

The "All - none" difference is quite striking - I double-checked the query and I'm pretty sure I'm pulling the right data. 

`sum(case when (((answer481 = 11749) OR (answer590 = 12123)) AND (answer483 IN (11659))) then 1 else 0 end) AS NoneAll,`

The "Family + Someone" (compound field) I _think_ is the results of some Who/Who-else stuff. For example, looking at the "All" data, Family=20 and Someone=20, so I expect Family+Someone=40. But, the query returns Family+Someone=37. I'm pretty sure this is due to the way the query is constructed:

`sum(case when (((answer481 IN (11641,11642)) OR (answer590 IN (12119,12120))) AND (answer483 IN (11659))) then 1 else 0 end) AS FamilySomeoneAll`

For example, what if a single survey respondent has "who=family" and "who else=someone" (is this possible?) If this happens, then the query above will only return 1, where running each on on its own will return 2. I _think_ this is the source of the difference.

How big of a deal is this? The other option would be to take the compound fields out of the query and calculate them afterwards, but I think that may be a significant task...

The "n" value are also quite different, but I think that might be an issue on your Google Sheet. The "n" values at the bottom of the table don't match up with the "n" values in cells k12:m12.

Thoughts?

-mike

**Comment by escoach** [comment]
@ultimike I think that I know what happened.

**Issue 1: "All - none" difference:** : I only pulled from 481, not from 590. I double-checked the actual survey and the skip logic will skip 590 (Who else) if 481 (Who) = none. I have no idea why there are 12 rows with Who = 0 and WhoElse = 1. After querying both 481 and 590, I got the same n that you used in your equation: 

- AllNone: 19
- TeamNone: 0
- MeNone: 2

My inclination would be to pull only 481 because 590 is trash. Thoughts?

**Issue 2: "Family...AND Business...**". Your query is correct. I added cell D6 + D8 (for ALL), which is close but running the query is cleaner. 

**Issue 3: the n value:** Your n probably is the number of response items, which is higher because of the WhoElse duplicates. Your approach is consistent with how we talked about the n. I should have been clearer when it comes to the Who/WhoElse data. I counted the number of "Finding jobs" events as the n (which is 71 for All). Rationale: I am counting the number of events or number of users who reported a specific event, which in this case is "Finding jobs" when interacting with one or more players.
I realize that this is the first time that you probably hear this. I think that comparing our data has been a very useful exercise to help bring up these key details.

It has been a long day and I've got to go. I hope that I have not added too much confusion especially with the Issue 3 about the n.

**Comment by ultimike** [comment]
## Issue 1: "All - none" difference

@escoach You wrote:

> My inclination would be to pull only 481 because 590 is trash. Thoughts?

Are you talking about removing all of the "Who else" stuff from all the queries?

## Issue 2: "Family...AND Business..."

> Your query is correct.

Excellent.

## Issue 3: the n value

> I hope that I have not added too much confusion especially with the Issue 3 about the n.

I'm confused 😄 

I'm not sure what the path forward is - especially in the context of Issue 1 above. Looking at the data on your Google sheet, I am not sure how you came up with a value of 71 in cell D12.

-mike

**Comment by escoach** [comment]
@ultimike 

**Issue 1: AllNone difference.** I meant to say delete "OR (answer590 = 12123))" from the query. 

Rationale: If a user responded **"None"** to "Who was the interaction with", then the response to "Who else was involved?" must be **"None"** as well. This means that the user was "Finding jobs" while **he was alone**. If we count both 481=11749 and 590 = 12123 it's like saying that the user was "Finding jobs" while he was **alone twice at the same time**, which does not make lot of sense.
Is this explanation helpful?

**Issue 3, the n value:** The value of n = 71 in cell D12 is the sum of 483 =11659 (Finding, securing jobs). 

The general rule for determining the value of n is that it should always be the number of activities reported by the users regardless of who they were interacting with or where they were. 

For the scenario ["What = ....." AND "Who = Any interaction" described in Example 1, GitHub 11 ](https://github.com/communityinclusion/escoach/issues/11) n = the number of times that 483 = 11659 i.e. number of times the user was "Finding, securing jobs".  

Is this explanation helpful?

I am happy to run a few more scenarios for you to check if we are on the same page with the calculations. Would that help?

**Comment by ultimike** [comment]
@escoach

## Issue 1: AllNone difference

I understand now. Thanks for the explanation. So, as a general rule, we should never count the "Who else" for "None" expressions (All/Provider/Me) in the "Who summary", correct? No other summaries (Where/What/Selected-activities) are affected by this change, correct?

I've updated the "Who summary (1 query)" tab of [my Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit) with the updated numbers for your review (they match yours now).

## Issue 3, the n value

I understand your logic, and have added three more expressions for `nAll`, `nProvider`, and `nMe` to the "Who summary" query. The results match yours. Again, see the "Who summary (1 query)" tab of my Google Sheet.

To confirm, n-values are always sums of only the selected "What" value(s), correct?

For the other queries (What/Where/Selected-activities), to calculate the n values, we are currently summing the values in the column. I tested it with the new n-expressions and the n-values are the same - do you have a preference?

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike 
**Issue 1: AllNone difference**
Mike wrote "_...So, as a general rule, we should never count the "Who else" for "None" expressions (All/Provider/Me) in the "Who summary", correct?..._"
Alberto: Correct.

Mike wrote: "..._No other summaries (Where/What/Selected-activities) are affected by this change, correct?._.."
Alberto: Yes and no, as long as they do not include a "None" component. For example the numerator of (**What = Finding jobs  AND Who = None**) is the sum of ((483 = 11659) and (481 = 11749)). It **does NOT include (590 = 12123).**

**Issue 3, the n value**
Mike wrote: "..._To confirm, n-values are always sums of only the selected "What" value(s), correct?.._."
Alberto: Correct. Counting the "What" activities is the best way to determine the n for the bottom row of the table.  

Mike wrote: "..._For the other queries (What/Where/Selected-activities), to calculate the n values, we are currently summing the values in the column. I tested it with the new n-expressions and the n-values are the same - do you have a preference?_..."
Alberto: I do not have preferences. Whatever is simpler for you works for me. 

Thank you for your patience as we go through this process. This is my first time doing this kind of database development. Knowing what I know now, next time I would provide more specifications. I realize that your job is to develop the code, not necessarily to guess what we need. Next, I am going to run a few more scenarios/examples for you to check if the equations make sense.

**Comment by ultimike** [comment]
## Issue 1: AllNone difference

Understood. I believe we need to always remove the "Who else" data from the "Who | None" option. I've created issue #47 for @mgcobblestone to make this happen.

## Issue 3, the n value

Understood, I have opened issue #48 for @mgcobblestone.

-mike

**Comment by escoach** [comment]
@ultimike Not sure if it is useful, but I added 8 tables with hrs and "n", representing a couple of scenarios for each of the three examples types. See [my Google sheet, see the tab "Aug 22](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=34647741)". Hopefully these tables help to confirm that we are on the same page as far as the equations.

Note that my weekly hours are not exactly five times the daily hrs. Similarly, when tables have only two rows, the second row is not exactly the complement to the first row so the total is not 8 hrs (e.g. see row 68). Probably this is due to rounding issues in excel. But I noticed that your dashboard takes care of this issue. I appreciate it. 

Paul brought up the issue that the “- -“ in the "Who" and "Where" drop down menus can be confusing. I would be inclined to replace  “- -“ with “No selection”. Makes sense? Better ideas?

At some point when you can, could you organize the columns in the table from “All”, "My Team" and “Me”?  Rationale: Righ not they are organized as "All", "Me", and "My team". It would make more sense for users to see a progression from bigger picture (All data) to My team data and finally My data.

**Comment by ultimike** [comment]
@escoach I went through your 8 new examples and created corresponding queries and sample tables.  Six of them show the same results. The two with differences are:

- WHERE=Anyplace, WHAT= "Networking" OR "Informational interview or business tour" OR "Engaging with businesses/job negotiation" AND Any place, [located on the "Where summary (1 query)" tab of my Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=1457665355). Note the discrepancies are limited to some of the the "My team" data values.
- "Who = Family, friends, or acquaintances of a person I support AND What = “Observing a job seeker" OR “Participating in an activity with the job seeker” OR “Informational interview or a business tour". , [located on the "Selected activities (1 query)" tab of my Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=1457665355). 

Thoughts?

I've created issue #49 for the "No selection" stuff.

I've created issue #50 for the column order change request.

-mike

**Comment by ultimike** [comment]
@escoach Outstanding.

@mgcobblestone I'm attaching a text document with the validated queries for the 8 examples that Alberto and I are talking about. Feel free to use them to double-check things as you go.

[martin-8-sample-queries.txt](https://github.com/communityinclusion/escoach/files/7037363/martin-8-sample-queries.txt)

thanks,  
-mike

**Comment by ultimike** [comment]
I think we're all set here. Closing.
