### ISSUE TITLE
Dashboard behavior when user isn't part of a team and has no data

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#60]
I stumbled upon this issue after getting things going on https://www.es-coach.org/dashboard, as I was logged in as myself - a user who is part of the "ICI" team but has no individual data. 

On https://www.es-coach.org/dashboard, with default values:

- Who: no selection
- Where: no selection
- What: no selections

The only row in the data table is "Total respondents".

I then created a new user on my local dev environment and went to the /dashboard page and with default values, the data table appeared as expected. Is the `surveycampaign_results` table on https://www.es-coach.org/ different than the one I have on my local? 

-mike

**Comment by thinkcollege** [comment]
@ultimike The survey_results table on the live site gets updated daily when cron runs about 7:30 AM from the surveycampaign module's cron function.  Let me know if you want an updated table, or if it would be better to set up the development site to keep running that without doing any of the other cron things like starting new survey campaigns. I could do that too.

**Comment by ultimike** [comment]
@thinkcollege I'm not sure what the solution is, but the query results aren't correct on https://www.es-coach.org/, but all is working fine on both my local and http://sp-escoach.communityinclusion.org/ 

I'm pretty sure something is up with the data on https://www.es-coach.org/, and I'm not sure how to diagnose the issue.

Unless you have any ideas, please send me a mysql dump of the `surveycampaign_results` table from https://www.es-coach.org/ and I'll see if I can figure out what is going on.

-mike

**Comment by thinkcollege** [comment]
@ultimike Here it is.  This table has been a dump for all sorts of experiments, so I am not surprised you are getting odd results.
[surveycampaign_results.zip](https://github.com/communityinclusion/escoach/files/7121849/surveycampaign_results.zip)

**Comment by ultimike** [comment]
@thinkcollege Thanks for the table.

@escoach I changed your password on the https://www.es-coach.org/ site to "migliore" so that I can login as you and take a look at some real-ish data (my account has no survey results data).

I figured out and fixed what was going on with the data on the https://www.es-coach.org/dashboard - this was caused by incomplete configuration of the what/who/where vocabularies. Once fixed, all the data is now showing up as I expect.

@thinkcollege if you agree that things look good (open issues notwithstanding), please close this task.

thanks,  
-mike

**Comment by thinkcollege** [comment]
@ultimike @escoach  This may be an entirely new issue.  Correct me if I am wrong @escoach but the expected behavior is that the dashboard is visible to anonymous users, showing only 'All' data.  Right now, on dev or live you get a database error when you go to /dashboard when not logged in. Either this error needs to be corrected, or we block anonymous users from /dashboard.  Here is the error in watchdog:
`Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens: SELECT count(*) AS TotalAll, sum(case when answer483 IN (:value0) AND email = :email then 1 else 0 end) AS JobSeekerMe, sum(case when answer483 IN (:value1) AND email = :email then 1 else 0 end) AS FindingMe, sum(case when answer483 IN (:value2) AND email = :email then 1 else 0 end) AS BeforeMe, sum(case when answer483 IN (:value3) AND email = :email then 1 else 0 end) AS AfterMe, sum(case when answer483 IN (:value4) AND email = :email then 1 else 0 end) AS StaffMe, sum(case when answer483 IN (:value5) AND email = :email then 1 else 0 end) AS DayMe, sum(case when answer483 IN (:value6) AND provider = :provider then 1 else 0 end) AS JobSeekerProvider, sum(case when answer483 IN (:value7) AND provider = :provider then 1 else 0 end) AS FindingProvider, sum(case when answer483 IN (:value8) AND provider = :provider then 1 else 0 end) AS BeforeProvider, sum(case when answer483 IN (:value9) AND provider = :provider then 1 else 0 end) AS AfterProvider, sum(case when answer483 IN (:value10) AND provider = :provider then 1 else 0 end) AS StaffProvider, sum(case when answer483 IN (:value11) AND provider = :provider then 1 else 0 end) AS DayProvider, sum(case when answer483 IN (:value12) then 1 else 0 end) AS JobSeekerAll, sum(case when answer483 IN (:value13) then 1 else 0 end) AS FindingAll, sum(case when answer483 IN (:value14) then 1 else 0 end) AS BeforeAll, sum(case when answer483 IN (:value15) then 1 else 0 end) AS AfterAll, sum(case when answer483 IN (:value16) then 1 else 0 end) AS StaffAll, sum(case when answer483 IN (:value17) then 1 else 0 end) AS DayAll FROM {surveycampaign_results} surveycampaign_results WHERE answer483 != :db_condition_placeholder_0; Array ( [:db_condition_placeholder_0] => NULL [:value0] => 11658 [:value1] => 11659 [:value2] => 11661 [:value3] => 11660 [:value4] => 11663 [:value5] => 11662 [:value6] => 11658 [:value7] => 11659 [:value8] => 11661 [:value9] => 11660 [:value10] => 11663 [:value11] => 11662 [:value12] => 11658 [:value13] => 11659 [:value14] => 11661 [:value15] => 11660 [:value16] => 11663 [:value17] => 11662 ) in Drupal\survey_dashboard\Form\DashboardForm->buildForm() (line 87 of /home/ici/escoach.communityinclusion.org/escoach/web/modules/custom/survey_dashboard/src/Form/DashboardForm.php).`

**Comment by ultimike** [comment]
@thinkcollege @escoach The easier solution would be to make the /dashboard not available to anonymous users 😄 

I'm pretty sure the issue above is related to the fact that we don't have a user, therefore we don't have an email address or a provider for the user, therefore the query fails due to missing email and provider arguments.

@mgcobblestone What do you think? What is the level of effort in order the data table to only show the "All" column for anonymous users? Maybe we can set a default empty string email and provider when the user is anonymous? If that gets us past this error, then we need to figure out how best to hide the "Me" and "My team" data, correct?

-mike

**Comment by mgcobblestone** [comment]
@ultimike There was an error in the logic for the way args/placeholders are handled.  Fix is up.

**Comment by ultimike** [comment]
Hmm - I'm getting a WSOD on http://sp-escoach.communityinclusion.org/dashboard as an anonymous user...

-mike

**Comment by thinkcollege** [comment]
@ultimike Talked this over with @escoach and he does want the dashboard visible showing All data only for anonymous users. As @mgcobblestone mentioned above, a dummy user could be inserted in place of the anonymous user.  If restructuring the table view were a lot of work you could let the anonymous user see the Observer data, and we could put a message on the page saying team data is for demonstration purposes only.

**Comment by ultimike** [comment]
> @ultimike There was an error in the logic for the way args/placeholders are handled. Fix is up.

@mgcobblestone I'm still seeing the WSOD when visiting /dashboard as an anonymous user. Same error as before. 

> Talked this over with @escoach and he does want the dashboard visible showing All data only for anonymous users.

@thinkcollege so if we hide the "Me" and "My team" data from anonymous users on any data table, we're good, correct?

-mike

**Comment by escoach** [comment]
@ultimike 
@thinkcollege asked that I respond. Yes, hiding the “me” and “my team” columns from anonymous users (i.e. the general public) works. I understand that the general public will see the "All" data of the real users, **excluding the "Observers" data**. Let us know if this is confusing.

**Comment by ultimike** [comment]
@escoach Understood.

@mgcobblestone No more WSOD, but the page loads with a PHP Notice:

> Notice: Undefined variable: profile in Drupal\survey_dashboard\Service\QueryBuilder->getProvider() (line 263 of modules/custom/survey_dashboard/src/Service/QueryBuilder.php).

Seems like a quick fix.

Once that is fixed, thoughts about hiding the "Me" and "My team" data? I see that it is all zeros. We can probably add some classes to the table columns then hide them with CSS. Thoughts on this or another approach?

-mike

**Comment by ultimike** [comment]
Assigning to @mgcobblestone

**Comment by mgcobblestone** [comment]
@ultimike Fix is in place for getProvider warning.  Me/Provider columns are now hidden for anonymous users.

**Comment by ultimike** [comment]
@mgcobblestone I made a few additional tweaks to get rid of the PHP Notices (I was still seeing some). I also tweaked the templates - the "colspan" variable ended up with extra quotes when rendered (odd).

Pushed to the 'devel' branch.

@thinkcollege @escoach Are we good-to-go with the anonymous dashboard display?

-mike

**Comment by thinkcollege** [comment]
@ultimike, @escoach  I pushed all devel changes to the live site, and turned off twig debugging on the live branch.

**Comment by escoach** [comment]
@ultimike after seeing the anonymous (public) dashboard display, I  realized that hiding the My Team and Me data is not optimal. Our team has a meeting tomorrow, we will discuss, and get back to you.

**Comment by escoach** [comment]
@ultimike I need to backtrack on the anonymous (public) dashboard visual. Could you reverse to make the "My team" and "Me" columns visible? I know they are filled with zeros. Is there a simple way to replace the zeros with something like a dash or "na" and without investing too much time into it? Otherwise, let's show the zeros for now and see how it looks.
 
Rationale: The "My team" and "Me" columns, even if empty, communicate to future potential users that the dashboard is more than just the "All" data. We will add text to tell these potential future users that if they register to receive the daily survey, they will be able to see numbers in those columns and compare their own and their team data with "All". 
Thank you for your patience.

**Comment by ultimike** [comment]
@escoach As a test, modified only the "Who summary" with this change. Please review on the Dev site and let me know if this is what you're looking for.

-mike

**Comment by escoach** [comment]
@ultimike yes, this looks great. If there is an easy way to make the columns the same width, that would be great. But for now, this works.
![image](https://user-images.githubusercontent.com/83360935/133851791-a81be1c3-0aa2-47c5-bea0-45c5542915b6.png)

**Comment by ultimike** [comment]
@escoach I have re-added the Team and Me columns to all Dashboard results and have adjusted the table and column widths.

The changes have been pulled into the Dev environment.

-mike

**Comment by escoach** [comment]
Looks great! I am closing this.
