### ISSUE TITLE
My data and my team data = 1

### ISSUE THREAD

**Issue by escoach** [communityinclusion/escoach#67]
@ultimike I just noticed that both the Dev site http://sp-escoach.communityinclusion.org/dashboard and the Live site https://www.es-coach.org/dashboard# show only 1 as the number of responses for "me" and "my team".
I am pretty sure this was not the case in the past. Thoughts?

Live site
![image](https://user-images.githubusercontent.com/83360935/133489595-e438b253-d2a0-4534-ba9e-afc7b93b238d.png)

Dev site
![image](https://user-images.githubusercontent.com/83360935/133489705-6d87de1f-2e3e-4940-bf02-1f6d75d40fd8.png)

**Comment by escoach** [comment]
@ultimike sorry to bother you, but apparently, Paul changed something in the system that would legitimately explain this issue. Most likely I will close this task without the need of you taking action. Again, thank you for your patience with this likely false alarm.

**Comment by ultimike** [comment]
@mgcobblestone ☝️

**Comment by escoach** [comment]
@ultimike Paul told me that everything looks good on his side. Could you check on your side?

**Comment by ultimike** [comment]
I'm not sure what you mean by "my side". If it looks good on the http://sp-escoach.communityinclusion.org/  site and the https://www.es-coach.org site, then I think we're good, no?

-mike

**Comment by thinkcollege** [comment]
@ultimike @escoach  I don't have much understanding of the logic behind this, but I do see the phenomenon of "1" appearing as number of responses for Me and My Team when I am logged in on development and live site.  Code on es-coach.org, rack branch is up to date with sp-escoach.communityinclusion devel branch.  We have changed the Institute for Community Inclusion users to "Observer" but there are still several responses for users that I have tested--for instance, Alberto--under their former or current provider in the surveycampaign_results table on live or development.  I hope that clarifies rather than muddies things.  I will discuss as needed with @escoach if that helps.

**Comment by ultimike** [comment]
@thinkcollege Doh! This was all my fault. I mistakenly added a bug a couple of commits ago. 

I just found and fixed and pushed to Dev.

So sorry!

-mike

**Comment by ultimike** [comment]
I believe this is all fixed. Please confirm.

thanks,  
-mike

**Comment by thinkcollege** [comment]
Good.
