### ISSUE TITLE
Create charts

### ISSUE THREAD

**Issue by mgcobblestone** [communityinclusion/escoach#75]

**Comment by mgcobblestone** [comment]
@ultimike New commit is up for #7.  I think #2 will be addressed by assigning different colors to the who/where terms.

**Comment by thinkcollege** [comment]
@ultimike  The rp-escoach.communityinclusion.org site is running.  The deployment server was down, but it is running now.

**Comment by mgcobblestone** [comment]
@ultimike New commit is up.  "Either" options are removed from chart.

**Comment by ultimike** [comment]
@escoach @mgcobblestone Looks like you made some progress while I was not available - sweet!

@escoach Looking at the rp-escoach site, it looks like you updated the following colors:

* What - Any supports AFTER hire - changed to Black
* What - Paperwork, meetings, program business - changed to Silver

Did I miss any?

I've updated the color data in code so that when we pull this into the live site, the colors will remain the same.

Also - I've updated the color for the "Selected activities" chart to #C70039 as requested.

@escoach Ready for your review on rp-escoach.

-mike

**Comment by escoach** [comment]
@ultimike Question: a few days ago I replaced the color for "WHAT=Support after hire" [in the bar charts taxonomy](https://www.es-coach.org/taxonomy/term/203/edit?destination=/admin/structure/taxonomy/manage/what/overview). Will that color be automatically updated in the [development website](https://rp-escoach.communityinclusion.org/dashboard)? Or do you need to push the change? 

PS: I replaced "LimeGreen" with "ForestGreen"

**Comment by ultimike** [comment]
@escoach Yes, I have to codify things or they won't get transferred between environments. I just did so for this one.

thanks,  
-mike
