### ISSUE TITLE
"What" checkboxes hierarchical behavior

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#81]
Via email, from Paul:

`We would like it if checking/unchecking the top level category (Getting to know a job seeker) automatically checked/unchecked the subcategories underneath.`

@mgcobblestone Since you've handled the rest of the Javascript for this project, what do you think? How much time to complete?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike Should be able to knock this out in an hour.

**Comment by thinkcollege** [comment]
Do you mean composer install form_options_attributes?

**Comment by ultimike** [comment]
Nope. Just `composer install`.

-mike

**Comment by thinkcollege** [comment]
@ultimike  Oh, I see you added it to composer.json.  Nothing ever goes wrong with Composer...

**Comment by escoach** [comment]
Hi @ultimike thanks for the change. You did exactly what was asked. 

Could you also set it so that the scenario in the screenshot below cannot happen? 
In the screenshot below, a user selected the top item "Getting to know a job seeker". Then they decided to **deselect** "Talking...." and "Observing..." thinking that now they are getting the total time invested in all "Getting to know" activities except "Talking" and "Observing". However, that would be **incorrect**. The dashboard will still show the total time "Getting to know job seeker". Makes sense?
![image](https://user-images.githubusercontent.com/83360935/149537520-9e2644f7-1034-40a4-a56c-7f78790ea9df.png)
   
I am not sure what's the best technical solution. But essentially, here is what should happen:

- A user select the top level item (e.g. Getting to know..."). Then all sub-items below are automatically selected.
- After selecting a top level item (e.g. Getting to know...") a user, **deselect** one or more sub-items below. Then the top level item (e.g. "Getting to know") gets deselected as in the screenshot below.
- 
![image](https://user-images.githubusercontent.com/83360935/149538616-fd39b767-8baa-4ed2-805a-4b4bab688589.png)

@thinkcollege keeping you in the loop

**Comment by ultimike** [comment]
@thinkcollege @escoach Which has priority? This additional change or #83, #84, or #85? We're dealing with a limited about of development time left...

-mike

**Comment by escoach** [comment]
@ultimike yes please complete this before starting the other tasks. 
However, once this is done, the priority should be the second item in @thinkcollege email (labels the horizontal axis as months e.g. Jul.-Sept. 2021, Oct.-Dec. 2021 instead of Q1, Q2 etc).
![image](https://user-images.githubusercontent.com/83360935/149542930-494ec6a1-4664-458b-ac26-bebd85b97991.png)

Then #83, #84, or #85 in that order. 
We are aware that there are limited hours available. If you feel that #83, #84, and #85 are not feasible with the time available, it's ok to not do them.

**Comment by mgcobblestone** [comment]
@ultimike @escoach New fix is up.

**Comment by ultimike** [comment]
@mgcobblestone I'm seeing the change on my local, but once again, I'm not seeing it on the dev site - I'm going to guess there's another deployment snafu.

So, I pushed a meaningless change and waited... still nothing...

@thinkcollege Help?!

-mike

**Comment by thinkcollege** [comment]
A push went through successfully 10 minutes ago.

**Comment by thinkcollege** [comment]
![Screenshot from 2022-01-14 15-21-01](https://user-images.githubusercontent.com/1806420/149580031-80d6b115-321b-4d17-8130-78ee3088a5f0.png)

**Comment by ultimike** [comment]
Hmm - @mgcobblestone I'm not sure why it isn't working on the dev site - can you look into it?

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike the development site http://sp-escoach.communityinclusion.org/dashboard has something else going on: It does not show the "All" data? Is it only on my computer?

![image](https://user-images.githubusercontent.com/83360935/149587127-ca79c45b-f66b-4106-b6b0-7b7b4b7e8c99.png)

**Comment by mgcobblestone** [comment]
@ultimike I am seeing the change on DEV.  Maybe a caching issue on your end?

**Comment by escoach** [comment]
@ultimike @mgcobblestone I cleared the cache and tried also in Firefox and Edge (normally I use Crome), but no luck.

**Comment by thinkcollege** [comment]
I also don't see any "All" data when I log into the dev site.  Not when I am logged in or as an anonymous user.

**Comment by ultimike** [comment]
I think part of the issue is my confusion between the old rp-escoach dev site and the newer sp-escoach dev site. I believe we all should only be looking at the sp-escoach site, someone correct me if I'm wrong.

My local, looking at the latest commit on the `devel` branch (df42bfeca098668f) is working fine. The checkbox behavior is working as intended and "All" data is displaying. 

The sp-escoach site checkbox behavior appears to be correct, but as @thinkcollege and @escoach mentioned, there is no "All" data displaying. This is very odd because there is "All" data on my local. @thinkcollege, has something changed in the results table that I'm not aware of?

-mike

**Comment by thinkcollege** [comment]
The rp-escoach.communityinclusion.org name is newer.  sp-escoach... is the earlier name but they are both the same site.  sp-escoach.communityinclusion.org just redirects to rp-escoach.   I am still not seeing the All data going to either domain name.  But I do see my own data when I log in to the dev site.  I don't understand how that is possible.  If there is data in the system it should show up for All.

**Comment by thinkcollege** [comment]
Here's a thought.  Maybe there are no providers on the dev site with registration codes > 10,000.  That would make the all data hidden.

**Comment by thinkcollege** [comment]
@ultimike @escoach That was in fact the case.  I just ran a quick DB query giving 'The STAR Center' provider a regcode value of 10001 and now All is showing up in the data and chart.

**Comment by ultimike** [comment]
@thinkcollege Very good - so is there anything else to do with this task or are we done here?

-mike

**Comment by escoach** [comment]
@ultimike @thinkcollege 
The Checking/unchecking of the parent/child items works well. Done.
The "All" data shows up in the default chart and table. Good.
 
However, when I select items, I get strange charts and tables. See the screenshot below from http://sp-escoach.communityinclusion.org/dashboard: The chart is split into two whereas the table shows strange numbers in the cell for "All", for "Other activities" (-30.32 in the example below). 

![image](https://user-images.githubusercontent.com/83360935/149832074-4fd4dcdc-33fc-4725-9924-40a0952d3382.png)

PS: Not sure if at this point is relevant, but note that the [development site](http://sp-escoach.communityinclusion.org/dashboard) MUST include providers with regcode > 10,000. In fact, we tested it to make sure that indeed only regcode > 10K were counted in the "All" data.
Another strange thing is that when we tested the regcode > 10K, [the default table showed 1,253 "All" responses see the Google spreadsheet](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=93699484) whereas the dev site default table right now shows only 19 "All" responses. 

![image](https://user-images.githubusercontent.com/83360935/149834252-72f9254c-895b-4f5e-901b-f4ca9b875c18.png)

**Comment by thinkcollege** [comment]
@escoach @ultimike  I added some more sample values to the surveycampaign_results table on the development site and those negative values you were seeing went away.  Don't get too concerned about that.  There should be enough > 10000 values in the table now to show reasonable results--but there may be some oddities.

**Comment by thinkcollege** [comment]
@ultimike It is looking pretty good.  I will move the changes over to the live site some time today.  That is the only way to see if there are any errors in the dashboard output.  If we find any problems there we do our own debugging before we hand tasks off to you.

**Comment by thinkcollege** [comment]
@ultimike @escoach Things are looking good on the dashboard on the live site.  The one problem I see is the Submit button at the bottom of the form doesn't submit.  When you select the Submit button at bottom it clears the form.  The Submit at the top works properly.

**Comment by ultimike** [comment]
@mgcobblestone Can you take a look at the submit button issue?

thanks,  
-mike

**Comment by ultimike** [comment]
@thinkcollege @escoach This should be all set. Please confirm.

thanks,  
-mike

**Comment by thinkcollege** [comment]
Nice work!
