### ISSUE TITLE
Add "clear all" button

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#83]
From @thinkcollege via email:

```
Add a "Clear all" button next to (or right below) the "Submit button. Rationale: Some users might not realize that they need to clear all selections and then click submit to get to the home default chart. A true "Clear all" that clears all selections under What, Who, Where, and Time Frame, prominently placed at top, bottom, or both would help.
```

@mgcobblestone What say you? Time estimate?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike Fix is up

**Comment by ultimike** [comment]
@mgcobblestone Hitting the "Clear all" button a second time results in a PHP Warning on my local:

`Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple() (line 261 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).`

-mike

**Comment by mgcobblestone** [comment]
@ultimike New fix is up

**Comment by ultimike** [comment]
@mgcobblestone Looks good - thanks.

@thinkcollege @escoach Ready for testing on the dev site.

-mike

**Comment by escoach** [comment]
@ultimike @thinkcollege 
Looks good. Two questions. 

- Would it be complicated to set it so that when a user clicks "Clear all" the dashboard shows the default view without the need for further action? Right now clicking on "Clear All" will deselect all items. But the dashboard data does not change, unless the user clicks also on "Submit". In some cases, some users might be confused.
- Could the "Clear All" button be colored to be distinguishable from the other buttons? How about Gray?

**Comment by mgcobblestone** [comment]
@ultimike @escoach Update is up - Clear All now submits default query, color is updated

**Comment by escoach** [comment]
@ultimike @mgcobblestone Work well, very nice! Done.

**Comment by ultimike** [comment]
Very good - marking as closed.

-mike
