### ISSUE TITLE
Current db for es-coach

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#89]
@ultimike 
Here is the db for the live siite (rack branch).  Code and db are in pretty good shape for D10.  A few modules need updates or are questionable.
[escoach_7_21_23.zip](https://github.com/communityinclusion/escoach/files/12130038/escoach_7_21_23.zip)

**Comment by ultimike** [comment]
@thinkcollege Thanks for this - I have re-cloned the site, checked out the `devel` branch and imported the DB you attached above, but there are some issues getting my local site running.

I am unable to login to the live site to confirm some things, so if you could create/update my user account there, it would be helpful. 

First off - please confirm this site is still running Drupal 9. I ask because looking at the composer.json file, I see entries for both drupal/core-recommended and drupal/core (which is very odd), but other core components are versioned to Drupal 8:

``` 
        "drupal/core-composer-scaffold": "^8.9.1",
        "drupal/core-project-message": "^8.8",
```

I can login to the site on my local (using `drush uli`, but when I try to go to the Status Report page:

```
Http\Discovery\Exception\NotFoundException: No PSR-18 clients found. Make sure to install a package providing "psr/http-client-implementation". Example: "php-http/guzzle7-adapter". in Http\Discovery\Psr18ClientDiscovery::find() (line 27 of /var/www/html/vendor/php-http/discovery/src/Psr18ClientDiscovery.php).
```

Which version of PHP should I be using on my local?

Is http://rp-escoach.communityinclusion.org still the dev site? I can login to this site, but I have the same issue with the Status Report page.

Tagging @mgcobblestone just so he is aware (Martin - nothing for you to do yet, but soon...)

thanks,
-mike

**Comment by thinkcollege** [comment]
See attached db: current live site.  I reset your password as 'changeme4567'
[escoach_7_31.zip](https://github.com/communityinclusion/escoach/files/12215834/escoach_7_31.zip)

The live and dev sites are both in D9.  I have been working through updating modules, including my custom mods.  Some module issues remain but I will deal with them.  And yes, you have the correct URL for the dev site.
Both live and dev sites are (rack and devel branches) are running PHP 8.1.  I am not sure about the errors you are getting.  I cleaned up the code a little.  The deployment was not set to remove files, which may have left some junk files.  I think I got all those.

**Comment by ultimike** [comment]
@thinkcollege the error I'm getting on the Drupal Status Report page has to do with Mailgun - it has a suggested dependency on `php-http/guzzle6-adapter` - if I `composer require` this, then my site works as expected. Mind if I commit this change?

Also - thanks for the fresh DB, PHP info, and the updated live site password (I've updated it).

-mike

**Comment by thinkcollege** [comment]
Yes, go ahead and add and commit guzzle6-adapter.  Let me know what branches you commit on and I will add that to the live "rack" branch, or you can commit to rack yourself.

**Comment by ultimike** [comment]
@thinkcollege I just committed and pushed it to the `devel` branch.

thanks,
-mike

**Comment by ultimike** [comment]
For some reason, I updated #102 with this info, but I'll repeat it here as well:

I just merged rack into devel and pushed the devel branch. @mgcobblestone and I will use devel as our working branch.

Closing this issue.

thanks,
-mike

**Comment by thinkcollege** [comment]
FYI, I did some updates on the rack branch (deployed to live site) to bring it closer to D10-ready.  We are in pretty good shape except for a few modules that are in alpha or not ready.  See attached current db for live site.
[escoach_9_6_23.zip](https://github.com/communityinclusion/escoach/files/12540201/escoach_9_6_23.zip)

**Comment by ultimike** [comment]
@thinkcollege Thanks for letting us know.

@mgcobblestone I have updated the `devel` branch with Paul's changes to `rack`. I also can confirm that the DB dump provided in the previous comment works with these updates on my local.

-mike

**Comment by thinkcollege** [comment]
@ultimike  Here is the live site db as of this morning.  I also included a separate dump of just the surveycampaign_results table.  The latter may be more useful to you because the live site database will probably cause conflicts with your development site.
[escoach_11_6_23.zip](https://github.com/communityinclusion/escoach/files/13269797/escoach_11_6_23.zip)
[surveycampaign_results_11_6_23.zip](https://github.com/communityinclusion/escoach/files/13269800/surveycampaign_results_11_6_23.zip)

**Comment by ultimike** [comment]
Closing. Obsolete. 

-mike
