### ISSUE TITLE
New home page - green arrow logic

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#99]
For the home page green arrow stuff, compare with previous month.

This means that for the overall home page display, we will have to run queries for both the current month and the previous month. See #96

**Comment by ultimike** [comment]
@thinkcollege Looking at the new es-coach_wireframe_Paul_edits_9_7-23.pdf, on page 1, there is a comment that "AFTER hire" has no "Better" symbol. Please confirm this means there should never been a green or blue star on the "AFTER hire" line.

-mike

**Comment by thinkcollege** [comment]
That is correct.

**Comment by thinkcollege** [comment]
The key under the tables that explains what the stars and other icons mean is going to be the same for all the different user views. One set of explanations for the Key Activities and one for the Best Practices table.  The icons are going to change too. The language and logic on the first set of tables for the anonymous user is closest to final.  The others have not been updated too well in the wireframe document.  I just got Alberto to work on finalizing the language, and Julie to come up with the icons we are going to use.  But the basic logic of "better than" is pretty well set, with no icons used for AFTER hire.

**Comment by ultimike** [comment]
@thinkcollege Any idea when we can expect the final-no-seriously-this-is-absolutely-the-most-final-one-ever-mockup.pdf file? 😜

**Comment by thinkcollege** [comment]
I have spent most of today lashing people to get that to you.  I wish I could tell you.  Maybe tomorrow.

**Comment by thinkcollege** [comment]
And I am sparing you most of the work of extracting that information.

**Comment by ultimike** [comment]
For the record, I am not an advocate of lashing or physical violence of any kind. Unless it is working.

Thanks for keeping me in the dark - I 110% do appreciate that.

-mike

**Comment by thinkcollege** [comment]
Mike here is a live demo of the dashboard design with corrected language, layout icons and other features: https://jreposa.github.io/index.html
That wireframe PDF was becoming hopelessly complicated.  I did not have the strength to redo it.  The above link gives you a clean look at the dashboard.  If there are logic and programming issues let's work them out in the Issues. 
Some important notes:

1. This is for design and layout purposes; some of the accessibility and other features may not be up to scratch.  This is using Bootstrap 5.  I plan to upgrade the current BS4 theme to 5, probably early next week.
2. The tabs above the header and logo (Mobile, Full; Anon, Manager...) are for demonstration purposes and are NOT to be included in the page as built by you.
3. The new header and main menu at the top will be implemented by us.  You should incorporate the sitewide headers and footers into your design and we will take care of them.
4. We have done away with the login box on the anonymous view in favor of a link that takes you to the login page.  It would be nice if we made the default page after login the dashboard, since that is the only real reason for people to log in.  This login message should go away for logged in users.
5. We have changed colors on the Google chart, using accessible colors.  The Google chart should be accessible.  That is, you should be able to tab into the chart elements and tooltips, if that is possible.
6. The page title incorporates text that will change when different providers or states are selected.  If this is unfeasible, we could leave out state or provider name from the title since it will be in the chart and table captions.
7. The State dropdown in the Anonymous view shows all states but in the actual site we want that select to be populated only by states that have data.
8. We have added a new icon for the # of Respondents row of the table, a triangle warning when # of respondents is less than 3.  That icon will not be used for the "Me" column in the table where, obviously, there can only be one respondent, but it is valid for all other "Team," "State," and "All" columns.
9. We did a lot of work on the notes under the tables.  They are the same for all four user views.  We sent this text to our copy editor so there might be slight changes in language but the logic they represent is sound.

**Comment by thinkcollege** [comment]
Just a note on the design mockup I sent last week (see above and https://jreposa.github.io/index.html).  In the mockup, for the anonymous user, the State selector disappears when you switch from the Key activities tab to the Best practices tab.  That should not happen.  The state selector should be present in both tab views, and should act on the data in both views when changed.  In the mockup, in the TA user view, the Provider selector shows the correct behavior remaining present in both tab views.  Again, this selector will change data in both tabs. We will update the mockup to correct this error in the anonymous view.

**Comment by ultimike** [comment]
Understood - this has all been accounted for. 

-mike

**Comment by ultimike** [comment]
I'm going to leave this issue open as it provides links to the most recent mockups.

-mike
